language: node_js
node_js:
  - "6.5"

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: KZNjtgFcXGt0uYOM+6Jr8NgM7xKocymsUUew7NENvFzUwby4lauXZupnpbs8dC2uApcCdc2jIHYguIWUOTnBXP3QJP4YswzgXUC9Ynrq66iW4sKicHbJLmY8bl2yCWefgKGJtOMl63fjhZ0pQL3yiWpQ7uwtkhXJ2XQ+ppzAWJWBaWMcpoAZonybDcdBubHY1zZ9s/6bFJRA/FtnomacSjGJDC/79/Qgo0VD88vtA1kL/ypqC4J5v9NDzEArYH/wMPHjbPt4NMWg6/q/mb4iPZXnVl43RAXDCnA9t6DwT4tksGKs+u6vAT0X1gTCMH30uXjVLJaFQk0H+/6CscvyW1olfl8CLSxHn825zi0CeI24GuarOVscgF0vxFzSEY7mC8WOU2EhzaaJyLHBuIHqnKozbMSVRSOBLVryk9YUC5V45CdEk7YNTMk1cCRAh5KpEzXsGRfhbThki53fwbzwAbzav56VkbjqQRnvVSKkXDYxrtiU68IWV/DgvdL3TRROm7wiN2f50lV5xIw/6OjZqB8x9Gygj9mXFB/GfrGyL7aMmduC/d0RC760VLaBLA3g1rMQN/ph8dLYR+FhlHzsu30nUTaVIsdA/7zoApNVXPcldY9gKocCVKcRdW9poCBAxkgb1YPUsTok+cr/CT8SfnNChkyNZrhyjcCdR2yY9PI=

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh

before_script:
- ./.build_scripts/lint.sh
- npm test

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
