language: node_js
node_js:
  - "6.9.4"

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: "EJJJclGX2TNXYdJe4A+rB3KFKYTaziq7VqgiphSku+oubVLTejVC1JzN4Ij6J/qUUY0azIDkeTClCiee54/uZl9d6tjHXt6zC7Ft4A4YqK+I/OzafIquUDibsUACMmxdDL+pK/88hzYIrB0Zi/VYLFtX8KyDYw8awketdWFq1COy6D2t7+gSg64M3ECqb6FNyyTbNRVerkAjH56PrGJsnXf6KIEtbro9wtRko62ngnCt+Tg2et53zSC5wK2R13CiqLXCxvosKkDzeFhekZh9pVEyuyx8SSAUk4RxGdKLLekD9eCOXzINhE39eLtf9/rP/9tpEhJ8Q/qiF2zTev8BY70sTpIf2Ks5j7MQ5zJG4NOZjrU/l+9ruTv5wU93yX18D3FcYJuZm7kIvHKMySxHLipTT6+O9ncN9hRxRt2VhLxYMpTrn9jAbO5RCwQpLYTeacxXxU2YbxpzVCXsRa55nRfVZNamlQ+XKSEK/V3DxFq0dRym0Wgk8SqVmLMm8HhtigzL1O6DV+az6lSWcts3MfExBNCS4YzspvNrOJSmq3rfEgxxGhTtbR1426ZSsix8E6jJCdiM2JwC+kZmG3ueWHjLOANI+UULame0MqKg8D2v8ks7EGxL+FnDWzUX0ujX+KpRoYWfcULmzArw0/OqzvYzqKMVlVDFilwhKvsRcDM="
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh

before_script:
- ./.build_scripts/lint.sh
- npm test

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
